import type { Metadata } from "next";
import {Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navbar";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['400', '700'], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${montserrat.variable}`}>
      <body className="antialiased">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
